name: Build and Push Docker Image  

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.kaidanima }}
          password: ${{ secrets.K21daN25442289 }}

      - name: Build Docker image
        run: docker build -t kaidanima/devops-demo:latest .

      - name: Push Docker image
        run: docker push kaidanima/devops-demo:latest

